build:
  script:
    - powershell -Command "Start-Sleep -Seconds 3"
    - echo "Build step completed"

# install_dependencies:
#   script:
#     - timeout /t 15
#     - echo "install dependencies step completed"

run_tests:
  script:
    - powershell -Command "Start-Sleep -Seconds 3"
    - echo "test step completed"

# security_scan:
#   stage: security
#   script:
#     - cd backend && npm audit --audit-level=high; exit 0